import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--phase', default='train', help="train/test")
parser.add_argument('--log_dir', default='model', help="storage of model")
parser.add_argument('--data_dir', default='data')#
parser.add_argument('--data_file', default='camel', help="filename without extension")
parser.add_argument('--dis_type', default='emd')#
parser.add_argument('--down_kernel', default='rs', help="rs or fps")#
parser.add_argument('--augment', type=bool, default=True)
parser.add_argument('--use_norm', type=bool, default=False)
parser.add_argument('--use_gan', type=bool, default=True)
parser.add_argument('--use_noise', type=bool, default=False)
parser.add_argument('--use_data', type=int, default=0, help="0: pu, 1:princeton, 2:kitti, 3: mpu dataset")
parser.add_argument('--restore', action='store_true')
parser.add_argument('--more_up', type=int, default=2)
parser.add_argument('--point_dim', type=int, default=3)
parser.add_argument('--training_epoch', type=int, default=51)
parser.add_argument('--batch_size', type=int, default=12)
parser.add_argument('--use_non_uniform', type=bool, default=False)
parser.add_argument('--jitter', type=bool, default=False)
parser.add_argument('--jitter_sigma', type=float, default=0.01, help="jitter augmentation")
parser.add_argument('--jitter_max', type=float, default=0.03, help="jitter augmentation")
parser.add_argument('--noise', type=float, default=0.01, help="noise sigma")
parser.add_argument('--up_ratio', type=int, default=4)
parser.add_argument('--base_lr_d', type=float, default=0.0001)
parser.add_argument('--base_lr_g', type=float, default=0.001)
parser.add_argument('--beta', type=float, default=0.9)
parser.add_argument('--start_decay_step', type=int, default=30)
parser.add_argument('--lr_decay_steps', type=int, default=30)
parser.add_argument('--lr_decay_rate', type=float, default=0.7)
parser.add_argument('--lr_clip', type=float, default=1e-6)
parser.add_argument('--steps_per_print', type=int, default=1)
parser.add_argument('--visulize', type=bool, default=True)
parser.add_argument('--steps_per_visu', type=int, default=10)
parser.add_argument('--epoch_per_save', type=int, default=50)
parser.add_argument('--use_repulse', type=bool, default=True)
parser.add_argument('--repulsion_w', default=1.0, type=float, help="repulsion_weight, default=1.0")
parser.add_argument('--fidelity_w', default=100.0, type=float, help="fidelity_weight, default=100.0")
parser.add_argument('--uniform_w', default=10.0, type=float, help="uniform_weight, default=10.0")
parser.add_argument('--gan_w', default=0.5, type=float, help="gan_weight")
parser.add_argument('--gen_update', default=2, type=int, help="gen_update")

FLAGS = parser.parse_args()

